Raise required compiler to rust 1.52
For unsafe_op_in_unsafe_fn lint.

    error[E0658]: the `unsafe_op_in_unsafe_fn` lint is unstable
      --> src/lib.rs:51:1
       |
    51 | #![allow(unsafe_op_in_unsafe_fn)]
       | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^