Raise minimum tested compiler to rust 1.63
Required by recent versions of libc.

    error: package `libc v0.2.164` cannot be built because it requires
    rustc 1.63 or newer, while the currently active rustc version is 1.61.0