Raise minimum tested compiler to 1.61
Required by transitive dev-dependency on zerocopy.

    error: package `zerocopy v0.6.6` cannot be built because it requires
    rustc 1.61.0 or newer, while the currently active rustc version is 1.52.0